---

- name: Create ANP
  hosts: NDO
  gather_facts: false
  vars:
    schema: Schema1
    template: Template1
    anp: AppProf-NetCentric
  tasks:

    - name: Create ANP
      cisco.mso.mso_schema_template_anp:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        template: "{{ template }}"
        schema: "{{ schema }}"
        anp: "{{ anp }}"
        state: present
        validate_certs: false
      delegate_to: localhost
