---
- name: gathering facts
  hosts: NDO
  gather_facts: false
  tasks:

    - name: Add VRFs
      include_tasks: 02_addVRF_inner.yml
      loop: "{{ templates }}"
      loop_control:
        loop_var: outer_item
      vars:
        templates:
          - template1
          - template2
          - template3
