---
- name: add VRF Contract
  hosts: NDO
  gather_facts: false
  vars:
    schema: schema1
    template: template1
  
  tasks:

    - name: Add a contract to a VRF
      cisco.mso.mso_schema_template_vrf_contract:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        schema: "{{ schema }}"
        template: "{{ template }}"
        vrf: "{{ item.vrf }}"
        contract:
          name: "{{ item.contract }}"
          type: "{{ item.type }}"
        state: present
      loop: 
        - { vrf: "vrf1", contract: "Any", type: "consumer" }
        - { vrf: "vrf1", contract: "Any", type: "provider" }
