---
- name: gathering facts
  hosts: NDO
  gather_facts: false
  tasks:

    - name: Add vzAny contract
      include_tasks: 06_addVRFContract_inner.yml
      loop: "{{ type }}"
      loop_control:
        loop_var: outer_item
      vars:
        type:
          - provider
          - consumer
