---
- name: gathering facts
  hosts: NDO
  gather_facts: false
  vars:
    tenant: Tenant1
    schema: Schema1
  tasks:

    - name: Add a new template to a schema
      cisco.mso.mso_schema_template:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        tenant: "{{ tenant }}"
        schema: "{{ schema }}"
        template: "{{ item }}"
        state: present
      loop:
        - Template1
        - Template2
        - Template3
