---

- name: getLayer3Out
  hosts: NDO
  gather_facts: false
  vars:
    schema: schema1
    template: template1
  tasks:

    - name: get L3Out
      cisco.mso.mso_schema_template_l3out:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
        schema: "{{ schema }}"
        template: "{{ template }}"
        state: query
      register: output

    - name: debug
      debug: 
        var: output
