---
- name: gathering facts
  hosts: NDO
  gather_facts: false
  tasks:

    - name: remove VRFs
      cisco.mso.mso_schema_template_vrf:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        schema: schema1
        template: template1
        vrf: "{{ item }}"
        state: absent
      loop:
        - vrf1
        - vrf2
        - vrf3
